### ISSUE TITLE
Questions regarding your efforts of running rust on ps vita

### ISSUE THREAD

**Issue by nikarh** [ZetaNumbers/vitasdk-rust#3]
Hi!

Recently I have managed to port Rust std for Vita via newlib from VITASDK. This effort is in the current rust-lang/rust master and is available on nightly.

I see you have a couple of repositories on the subject. Do you have any particular goals you want to achieve with that?
I wanted to ask the owner of https://github.com/vita-rust to get a co-ownership, and to improve support for what already is there, add some examples, and port some more complicated stuff if possible (network stack, async, etc)

Please let me know, if you are still interested and have time for improving Rust on Vita support.

**Comment by zetanumbers** [comment]
This repo is to be considered an old prototype. My efforts are focused on vita-rust.
